providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = '24.12.0'

[phases.setup]
nixPkgs = ['...', 'jq']

[phases.codegen]
dependsOn = ['install']
cmds = [
        'pnpm run prepare'
]

[phases.build]
dependsOn = ["...", "codegen"]
cmds = [
        'pnpm run build'
]

[start]
cmd = "node .output/server/index.mjs"

